/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jefeAcademia;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;



/**
 *
 * @author Caleb
 */
public class asistenciaIndividual {

    private int _idPersona = 0;
    private int _idTipo = 0;
    private String _numero = "";
    private String _nombre = "";
    private String _asistenciaIndividual = "";

    public asistenciaIndividual(int idPersona, int idTipo, String numero, String nombre) {
        _idPersona = idPersona;
        _idTipo = idTipo;
        _numero = numero;
        _nombre = nombre;
    }

    public String dibujarAsistenciaIndividual() {
        String htmlFinal = "";
        String scriptFinal = "";
        String scriptGeneral = "";
        //Ciclo 1
        String infoAgosto;
        int asistidosAgosto = 0, faltadosAgosto = 0, totalAgosto = 0;
        String infoSeptiembre;
        int asistidosSeptiembre = 0, faltadosSeptiembre = 0, totalSeptiembre = 0;
        String infoOctubre;
        int asistidosOctubre = 0, faltadosOctubre = 0, totalOctubre = 0;
        String infoNoviembre;
        int asistidosNoviembre = 0, faltadosNoviembre = 0, totalNoviembre = 0;
        String infoDiciembre;
        int asistidosDiciembre = 0, faltadosDiciembre = 0, totalDiciembre = 0;
        //Ciclo 2
        String infoEnero;
        int asistidosEnero = 0, faltadosEnero = 0, totalEnero = 0;
        String infoFebrero;
        int asistidosFebrero = 0, faltadosFebrero = 0, totalFebrero = 0;
        String infoMarzo;
        int asistidosMarzo = 0, faltadosMarzo = 0, totalMarzo = 0;
        String infoAbril;
        int asistidosAbril = 0, faltadosAbril = 0, totalAbril = 0;
        String infoMayo;
        int asistidosMayo = 0, faltadosMayo = 0, totalMayo = 0;
        String infoJunio;
        int asistidosJunio = 0, faltadosJunio = 0, totalJunio = 0;
        String infoJulio;
        int asistidosJulio = 0, faltadosJulio = 0, totalJulio = 0;
        //Necesarios para obtener informacion
        Calendar calendario = new GregorianCalendar();
        int mes = calendario.get(Calendar.MONTH);
        if (mes > Calendar.JULY && mes < Calendar.DECEMBER + 1) {//Ciclo 1
            if (mes > Calendar.JULY) {
                ArrayList<Object> datosAgosto = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(8)));
                infoAgosto = (String) datosAgosto.get(0);
                totalAgosto = (int) datosAgosto.get(1);
                asistidosAgosto = (int) datosAgosto.get(2);
                faltadosAgosto = (int) datosAgosto.get(3);
                htmlFinal = "<div class=\"mdl-cell mdl-cell--6-col\">\n"
                        + "                        <div class=\"tarjetas\" style=\"overflow: auto;\">\n"
                        + "                            <div class=\"descripcion graf\" style=\"\">\n"
                        + "                                <canvas id=\"" + Calendar.AUGUST + "\" class=\"grafica\"></canvas>\n"
                        + "                            </div>\n"
                        + "                        </div>\n"
                        + "                    </div>\n"
                        + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                        + "                        <div class=\"tarjetas tamanoMes\" style=\"\">\n"
                        + "                            <div class=\"descripcion ajusta\" style=\"\">\n"
                        + "                                <div style=\"background-color: red;\" class=\"tituloMes\"><br>Agosto</div>\n"
                        + "                                <div style=\"\" class=\"ajustarTabla\">\n"
                        + " " + infoAgosto + "\n"
                        + "                                </div>\n"
                        + "                            </div>\n"
                        + "                        </div>\n"
                        + "                    </div>";
                //Script para las graficas
                scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'line',\n"
                        + "\n"
                        + "                // The data for our dataset\n"
                        + "                data: {\n"
                        + "                    labels: [\"Meses\", \"Agosto\"],\n"
                        + "                    datasets: [{\n"
                        + "                            label: \"Días Asistidos\",\n"
                        + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                        + "                            borderColor: 'rgb(255, 80, 0)',\n"
                        + "                            data: [0, " + asistidosAgosto + ", " + totalAgosto + "],\n"
                        + "                        }]\n"
                        + "                },\n"
                        + "\n"
                        + "                // Configuration options go here\n"
                        + "                options: {}\n"
                        + "            });\n"
                        + "\n";
                scriptFinal = " \n"
                        + "            var ctx = document.getElementById('" + Calendar.AUGUST + "').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'bar',\n"
                        + "                data: {\n"
                        + "                    labels: [\"Asistidos\", \"No Asistidos\"],\n"
                        + "                    datasets: [\n"
                        + "                        {\n"
                        + "                            label: \"Días\",\n"
                        + "                            backgroundColor: [\"rgba(0, 176, 204, 0.2)\", \"rgba(255, 0, 0, 0.2)\"],\n"
                        + "                            borderColor: [\"rgb(0, 176, 204)\", \"rgb(255, 0, 0)\"],\n"
                        + "                            borderWidth: 3,\n"
                        + "                            data: [" + asistidosAgosto + ", " + faltadosAgosto + ", 0, " + totalAgosto + "]\n"
                        + "                        }\n"
                        + "                    ]\n"
                        + "                },\n"
                        + "                options: {\n"
                        + "                }\n"
                        + "            });";

            }
            if (mes > Calendar.AUGUST) {
                ArrayList<Object> datosSeptiembre = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(9)));
                infoSeptiembre = (String) datosSeptiembre.get(0);
                totalSeptiembre = (int) datosSeptiembre.get(1);
                asistidosSeptiembre = (int) datosSeptiembre.get(2);
                faltadosSeptiembre = (int) datosSeptiembre.get(3);
                htmlFinal += "<div class=\"mdl-cell mdl-cell--6-col\">\n"
                        + "                        <div class=\"tarjetas\" style=\"overflow: auto;\">\n"
                        + "                            <div class=\"descripcion graf\" style=\"\">\n"
                        + "                                <canvas id=\"" + Calendar.SEPTEMBER + "\" class=\"grafica\"></canvas>\n"
                        + "                            </div>\n"
                        + "                        </div>\n"
                        + "                    </div>\n"
                        + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                        + "                        <div class=\"tarjetas tamanoMes\" style=\"\">\n"
                        + "                            <div class=\"descripcion ajusta\" style=\"\">\n"
                        + "                                <div style=\"background-color: red;\" class=\"tituloMes\"><br>Septiembre</div>\n"
                        + "                                <div style=\"\" class=\"ajustarTabla\">\n"
                        + " " + infoSeptiembre + "\n"
                        + "                                </div>\n"
                        + "                            </div>\n"
                        + "                        </div>\n"
                        + "                    </div>";
                //Script para las graficas
                scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'line',\n"
                        + "\n"
                        + "                // The data for our dataset\n"
                        + "                data: {\n"
                        + "                    labels: [\"Meses\", \"Agosto\", \"Septiembre\"],\n"
                        + "                    datasets: [{\n"
                        + "                            label: \"Días Asistidos\",\n"
                        + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                        + "                            borderColor: 'rgb(255, 80, 0)',\n"
                        + "                            data: [0, " + asistidosAgosto + ", " + asistidosSeptiembre + ", " + totalAgosto + "],\n"
                        + "                        }]\n"
                        + "                },\n"
                        + "\n"
                        + "                // Configuration options go here\n"
                        + "                options: {}\n"
                        + "            });\n"
                        + "\n";
                scriptFinal += " \n"
                        + "            var ctx = document.getElementById('" + Calendar.SEPTEMBER + "').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'bar',\n"
                        + "                data: {\n"
                        + "                    labels: [\"Asistidos\", \"No Asistidos\"],\n"
                        + "                    datasets: [\n"
                        + "                        {\n"
                        + "                            label: \"Días\",\n"
                        + "                            backgroundColor: [\"rgba(0, 176, 204, 0.2)\", \"rgba(255, 0, 0, 0.2)\"],\n"
                        + "                            borderColor: [\"rgb(0, 176, 204)\", \"rgb(255, 0, 0)\"],\n"
                        + "                            borderWidth: 3,\n"
                        + "                            data: [" + asistidosSeptiembre + ", " + faltadosSeptiembre + ", 0, " + totalSeptiembre + ", " + totalAgosto + "]\n"
                        + "                        }\n"
                        + "                    ]\n"
                        + "                },\n"
                        + "                options: {\n"
                        + "                }\n"
                        + "            });";
            }
            if (mes > Calendar.SEPTEMBER) {
                ArrayList<Object> datosOctubre = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(10)));
                infoOctubre = (String) datosOctubre.get(0);
                totalOctubre = (int) datosOctubre.get(1);
                asistidosOctubre = (int) datosOctubre.get(2);
                faltadosOctubre = (int) datosOctubre.get(3);
                htmlFinal += "<div class=\"mdl-cell mdl-cell--6-col\">\n"
                        + "                        <div class=\"tarjetas\" style=\"overflow: auto;\">\n"
                        + "                            <div class=\"descripcion graf\" style=\"\">\n"
                        + "                                <canvas id=\"" + Calendar.OCTOBER + "\" class=\"grafica\"></canvas>\n"
                        + "                            </div>\n"
                        + "                        </div>\n"
                        + "                    </div>\n"
                        + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                        + "                        <div class=\"tarjetas tamanoMes\" style=\"\">\n"
                        + "                            <div class=\"descripcion ajusta\" style=\"\">\n"
                        + "                                <div style=\"background-color: red;\" class=\"tituloMes\"><br>Octubre</div>\n"
                        + "                                <div style=\"\" class=\"ajustarTabla\">\n"
                        + " " + infoOctubre + "\n"
                        + "                                </div>\n"
                        + "                            </div>\n"
                        + "                        </div>\n"
                        + "                    </div>";
                //Script para las graficas
                scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'line',\n"
                        + "\n"
                        + "                // The data for our dataset\n"
                        + "                data: {\n"
                        + "                    labels: [\"Meses\", \"Agosto\", \"Septiembre\", \"Octubre\"],\n"
                        + "                    datasets: [{\n"
                        + "                            label: \"Días Asistidos\",\n"
                        + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                        + "                            borderColor: 'rgb(255, 80, 0)',\n"
                        + "                            data: [0, " + asistidosAgosto + ", " + asistidosSeptiembre + ", " + asistidosOctubre + ", " + totalAgosto + "],\n"
                        + "                        }]\n"
                        + "                },\n"
                        + "\n"
                        + "                // Configuration options go here\n"
                        + "                options: {}\n"
                        + "            });\n"
                        + "\n";
                scriptFinal += " \n"
                        + "            var ctx = document.getElementById('" + Calendar.OCTOBER + "').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'bar',\n"
                        + "                data: {\n"
                        + "                    labels: [\"Asistidos\", \"No Asistidos\"],\n"
                        + "                    datasets: [\n"
                        + "                        {\n"
                        + "                            label: \"Días\",\n"
                        + "                            backgroundColor: [\"rgba(0, 176, 204, 0.2)\", \"rgba(255, 0, 0, 0.2)\"],\n"
                        + "                            borderColor: [\"rgb(0, 176, 204)\", \"rgb(255, 0, 0)\"],\n"
                        + "                            borderWidth: 3,\n"
                        + "                            data: [" + asistidosOctubre + ", " + faltadosOctubre + ", 0, " + totalOctubre + ", " + totalAgosto + "]\n"
                        + "                        }\n"
                        + "                    ]\n"
                        + "                },\n"
                        + "                options: {\n"
                        + "                }\n"
                        + "            });";
            }
            if (mes > Calendar.OCTOBER) {
                ArrayList<Object> datosNoviembre = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(11)));
                infoNoviembre = (String) datosNoviembre.get(0);
                totalNoviembre = (int) datosNoviembre.get(1);
                asistidosNoviembre = (int) datosNoviembre.get(2);
                faltadosNoviembre = (int) datosNoviembre.get(3);
                htmlFinal += "<div class=\"mdl-cell mdl-cell--6-col\">\n"
                        + "                        <div class=\"tarjetas\" style=\"overflow: auto;\">\n"
                        + "                            <div class=\"descripcion graf\" style=\"\">\n"
                        + "                                <canvas id=\"" + Calendar.NOVEMBER + "\" class=\"grafica\"></canvas>\n"
                        + "                            </div>\n"
                        + "                        </div>\n"
                        + "                    </div>\n"
                        + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                        + "                        <div class=\"tarjetas tamanoMes\" style=\"\">\n"
                        + "                            <div class=\"descripcion ajusta\" style=\"\">\n"
                        + "                                <div style=\"background-color: red;\" class=\"tituloMes\"><br>Noviembre</div>\n"
                        + "                                <div style=\"\" class=\"ajustarTabla\">\n"
                        + " " + infoNoviembre + "\n"
                        + "                                </div>\n"
                        + "                            </div>\n"
                        + "                        </div>\n"
                        + "                    </div>";
                //Script para las graficas
                scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'line',\n"
                        + "\n"
                        + "                // The data for our dataset\n"
                        + "                data: {\n"
                        + "                    labels: [\"Meses\", \"Agosto\", \"Septiembre\", \"Octubre\", \"Noviembre\"],\n"
                        + "                    datasets: [{\n"
                        + "                            label: \"Días Asistidos\",\n"
                        + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                        + "                            borderColor: 'rgb(255, 80, 0)',\n"
                        + "                            data: [0, " + asistidosAgosto + ", " + asistidosSeptiembre + ", " + asistidosOctubre + ", " + asistidosNoviembre + ", " + totalAgosto + "],\n"
                        + "                        }]\n"
                        + "                },\n"
                        + "\n"
                        + "                // Configuration options go here\n"
                        + "                options: {}\n"
                        + "            });\n"
                        + "\n";
                scriptFinal += " \n"
                        + "            var ctx = document.getElementById('" + Calendar.NOVEMBER + "').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'bar',\n"
                        + "                data: {\n"
                        + "                    labels: [\"Asistidos\", \"No Asistidos\"],\n"
                        + "                    datasets: [\n"
                        + "                        {\n"
                        + "                            label: \"Días\",\n"
                        + "                            backgroundColor: [\"rgba(0, 176, 204, 0.2)\", \"rgba(255, 0, 0, 0.2)\"],\n"
                        + "                            borderColor: [\"rgb(0, 176, 204)\", \"rgb(255, 0, 0)\"],\n"
                        + "                            borderWidth: 3,\n"
                        + "                            data: [" + asistidosNoviembre + ", " + faltadosNoviembre + ", 0, " + totalNoviembre + "]\n"
                        + "                        }\n"
                        + "                    ]\n"
                        + "                },\n"
                        + "                options: {\n"
                        + "                }\n"
                        + "            });";
            }
            if (mes > Calendar.NOVEMBER) {
                ArrayList<Object> datosDiciembre = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(12)));
                infoDiciembre = (String) datosDiciembre.get(0);
                totalDiciembre = (int) datosDiciembre.get(1);
                asistidosDiciembre = (int) datosDiciembre.get(2);
                faltadosDiciembre = (int) datosDiciembre.get(3);
                htmlFinal += "<div class=\"mdl-cell mdl-cell--6-col\">\n"
                        + "                        <div class=\"tarjetas\" style=\"overflow: auto;\">\n"
                        + "                            <div class=\"descripcion graf\" style=\"\">\n"
                        + "                                <canvas id=\"" + Calendar.DECEMBER + "\" class=\"grafica\"></canvas>\n"
                        + "                            </div>\n"
                        + "                        </div>\n"
                        + "                    </div>\n"
                        + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                        + "                        <div class=\"tarjetas tamanoMes\" style=\"\">\n"
                        + "                            <div class=\"descripcion ajusta\" style=\"\">\n"
                        + "                                <div style=\"background-color: red;\" class=\"tituloMes\"><br>Diciembre</div>\n"
                        + "                                <div style=\"\" class=\"ajustarTabla\">\n"
                        + " " + infoDiciembre + "\n"
                        + "                                </div>\n"
                        + "                            </div>\n"
                        + "                        </div>\n"
                        + "                    </div>";
                //Script para las graficas
                scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'line',\n"
                        + "\n"
                        + "                // The data for our dataset\n"
                        + "                data: {\n"
                        + "                    labels: [\"Meses\", \"Agosto\", \"Septiembre\", \"Octubre\", \"Noviembre\", \"Diciembre\"],\n"
                        + "                    datasets: [{\n"
                        + "                            label: \"Días Asistidos\",\n"
                        + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                        + "                            borderColor: 'rgb(255, 80, 0)',\n"
                        + "                            data: [0, " + asistidosAgosto + ", " + asistidosSeptiembre + ", " + asistidosOctubre + ", " + asistidosNoviembre + ", " + asistidosDiciembre + ", " + totalAgosto + "],\n"
                        + "                        }]\n"
                        + "                },\n"
                        + "\n"
                        + "                // Configuration options go here\n"
                        + "                options: {}\n"
                        + "            });\n"
                        + "\n";
                scriptFinal += " \n"
                        + "            var ctx = document.getElementById('" + Calendar.DECEMBER + "').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'bar',\n"
                        + "                data: {\n"
                        + "                    labels: [\"Asistidos\", \"No Asistidos\"],\n"
                        + "                    datasets: [\n"
                        + "                        {\n"
                        + "                            label: \"Días\",\n"
                        + "                            backgroundColor: [\"rgba(0, 176, 204, 0.2)\", \"rgba(255, 0, 0, 0.2)\"],\n"
                        + "                            borderColor: [\"rgb(0, 176, 204)\", \"rgb(255, 0, 0)\"],\n"
                        + "                            borderWidth: 3,\n"
                        + "                            data: [" + asistidosDiciembre + ", " + faltadosDiciembre + ", 0, " + totalDiciembre + "]\n"
                        + "                        }\n"
                        + "                    ]\n"
                        + "                },\n"
                        + "                options: {\n"
                        + "                }\n"
                        + "            });";
            }
        } else {
            if (mes > Calendar.JANUARY-1 && mes < Calendar.AUGUST) {//Ciclo 2
                if (mes > Calendar.JANUARY-1) {
                    ArrayList<Object> datosEnero = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(1)));
                    infoEnero = (String) datosEnero.get(0);
                    totalEnero = (int) datosEnero.get(1);
                    asistidosEnero = (int) datosEnero.get(2);
                    faltadosEnero = (int) datosEnero.get(3);
                    htmlFinal = "<div class=\"mdl-cell mdl-cell--6-col\">\n"
                            + "                        <div class=\"tarjetas\" style=\"overflow: auto;\">\n"
                            + "                            <div class=\"descripcion graf\" style=\"\">\n"
                            + "                                <canvas id=\"" + Calendar.JANUARY + "\" class=\"grafica\"></canvas>\n"
                            + "                            </div>\n"
                            + "                        </div>\n"
                            + "                    </div>\n"
                            + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                            + "                        <div class=\"tarjetas tamanoMes\" style=\"\">\n"
                            + "                            <div class=\"descripcion ajusta\" style=\"\">\n"
                            + "                                <div style=\"background-color: red;\" class=\"tituloMes\"><br>Enero</div>\n"
                            + "                                <div style=\"\" class=\"ajustarTabla\">\n"
                            + " " + infoEnero + "\n"
                            + "                                </div>\n"
                            + "                            </div>\n"
                            + "                        </div>\n"
                            + "                    </div>";
                    //Script para las graficas
                    scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'line',\n"
                            + "\n"
                            + "                // The data for our dataset\n"
                            + "                data: {\n"
                            + "                    labels: [\"Meses\", \"Enero\"],\n"
                            + "                    datasets: [{\n"
                            + "                            label: \"Días Asistidos\",\n"
                            + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                            + "                            borderColor: 'rgb(255, 80, 0)',\n"
                            + "                            data: [0, " + asistidosEnero + ", " + totalEnero + "],\n"
                            + "                        }]\n"
                            + "                },\n"
                            + "\n"
                            + "                // Configuration options go here\n"
                            + "                options: {}\n"
                            + "            });\n"
                            + "\n";
                    scriptFinal = " \n"
                            + "            var ctx = document.getElementById('" + Calendar.JANUARY + "').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'bar',\n"
                            + "                data: {\n"
                            + "                    labels: [\"Asistidos\", \"No Asistidos\"],\n"
                            + "                    datasets: [\n"
                            + "                        {\n"
                            + "                            label: \"Días\",\n"
                            + "                            backgroundColor: [\"rgba(0, 176, 204, 0.2)\", \"rgba(255, 0, 0, 0.2)\"],\n"
                            + "                            borderColor: [\"rgb(0, 176, 204)\", \"rgb(255, 0, 0)\"],\n"
                            + "                            borderWidth: 3,\n"
                            + "                            data: [" + asistidosEnero + ", " + faltadosEnero + ", 0, " + totalEnero + "]\n"
                            + "                        }\n"
                            + "                    ]\n"
                            + "                },\n"
                            + "                options: {\n"
                            + "                }\n"
                            + "            });";

                }
                if (mes > Calendar.JANUARY) {
                    ArrayList<Object> datosFebrero = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(2)));
                    infoFebrero = (String) datosFebrero.get(0);
                    totalFebrero = (int) datosFebrero.get(1);
                    asistidosFebrero = (int) datosFebrero.get(2);
                    faltadosFebrero = (int) datosFebrero.get(3);
                    htmlFinal += "<div class=\"mdl-cell mdl-cell--6-col\">\n"
                            + "                        <div class=\"tarjetas\" style=\"overflow: auto;\">\n"
                            + "                            <div class=\"descripcion graf\" style=\"\">\n"
                            + "                                <canvas id=\"" + Calendar.FEBRUARY + "\" class=\"grafica\"></canvas>\n"
                            + "                            </div>\n"
                            + "                        </div>\n"
                            + "                    </div>\n"
                            + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                            + "                        <div class=\"tarjetas tamanoMes\" style=\"\">\n"
                            + "                            <div class=\"descripcion ajusta\" style=\"\">\n"
                            + "                                <div style=\"background-color: red;\" class=\"tituloMes\"><br>Febrero</div>\n"
                            + "                                <div style=\"\" class=\"ajustarTabla\">\n"
                            + " " + infoFebrero + "\n"
                            + "                                </div>\n"
                            + "                            </div>\n"
                            + "                        </div>\n"
                            + "                    </div>";
                    //Script para las graficas
                    scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'line',\n"
                            + "\n"
                            + "                // The data for our dataset\n"
                            + "                data: {\n"
                            + "                    labels: [\"Meses\", \"Enero\", \"Febrero\"],\n"
                            + "                    datasets: [{\n"
                            + "                            label: \"Días Asistidos\",\n"
                            + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                            + "                            borderColor: 'rgb(255, 80, 0)',\n"
                            + "                            data: [0, " + asistidosEnero + ", " + asistidosFebrero + ", " + totalEnero + "],\n"
                            + "                        }]\n"
                            + "                },\n"
                            + "\n"
                            + "                // Configuration options go here\n"
                            + "                options: {}\n"
                            + "            });\n"
                            + "\n";
                    scriptFinal += " \n"
                            + "            var ctx = document.getElementById('" + Calendar.FEBRUARY+ "').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'bar',\n"
                            + "                data: {\n"
                            + "                    labels: [\"Asistidos\", \"No Asistidos\"],\n"
                            + "                    datasets: [\n"
                            + "                        {\n"
                            + "                            label: \"Días\",\n"
                            + "                            backgroundColor: [\"rgba(0, 176, 204, 0.2)\", \"rgba(255, 0, 0, 0.2)\"],\n"
                            + "                            borderColor: [\"rgb(0, 176, 204)\", \"rgb(255, 0, 0)\"],\n"
                            + "                            borderWidth: 3,\n"
                            + "                            data: [" + asistidosFebrero + ", " + faltadosFebrero + ", 0, " + totalFebrero + ", " + totalEnero + "]\n"
                            + "                        }\n"
                            + "                    ]\n"
                            + "                },\n"
                            + "                options: {\n"
                            + "                }\n"
                            + "            });";
                }
                if (mes > Calendar.FEBRUARY) {
                    ArrayList<Object> datosMarzo = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(3)));
                    infoMarzo = (String) datosMarzo.get(0);
                    totalMarzo = (int) datosMarzo.get(1);
                    asistidosMarzo = (int) datosMarzo.get(2);
                    faltadosMarzo = (int) datosMarzo.get(3);
                    htmlFinal += "<div class=\"mdl-cell mdl-cell--6-col\">\n"
                            + "                        <div class=\"tarjetas\" style=\"overflow: auto;\">\n"
                            + "                            <div class=\"descripcion graf\" style=\"\">\n"
                            + "                                <canvas id=\"" + Calendar.MARCH + "\" class=\"grafica\"></canvas>\n"
                            + "                            </div>\n"
                            + "                        </div>\n"
                            + "                    </div>\n"
                            + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                            + "                        <div class=\"tarjetas tamanoMes\" style=\"\">\n"
                            + "                            <div class=\"descripcion ajusta\" style=\"\">\n"
                            + "                                <div style=\"background-color: red;\" class=\"tituloMes\"><br>Marzo</div>\n"
                            + "                                <div style=\"\" class=\"ajustarTabla\">\n"
                            + " " + infoMarzo + "\n"
                            + "                                </div>\n"
                            + "                            </div>\n"
                            + "                        </div>\n"
                            + "                    </div>";
                    //Script para las graficas
                    scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'line',\n"
                            + "\n"
                            + "                // The data for our dataset\n"
                            + "                data: {\n"
                            + "                    labels: [\"Meses\", \"Enero\", \"Febrero\", \"Marzo\"],\n"
                            + "                    datasets: [{\n"
                            + "                            label: \"Días Asistidos\",\n"
                            + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                            + "                            borderColor: 'rgb(255, 80, 0)',\n"
                            + "                            data: [0, " + asistidosEnero + ", " + asistidosFebrero + ", " + asistidosMarzo + ", " + totalEnero + "],\n"
                            + "                        }]\n"
                            + "                },\n"
                            + "\n"
                            + "                // Configuration options go here\n"
                            + "                options: {}\n"
                            + "            });\n"
                            + "\n";
                    scriptFinal += " \n"
                            + "            var ctx = document.getElementById('" + Calendar.MARCH + "').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'bar',\n"
                            + "                data: {\n"
                            + "                    labels: [\"Asistidos\", \"No Asistidos\"],\n"
                            + "                    datasets: [\n"
                            + "                        {\n"
                            + "                            label: \"Días\",\n"
                            + "                            backgroundColor: [\"rgba(0, 176, 204, 0.2)\", \"rgba(255, 0, 0, 0.2)\"],\n"
                            + "                            borderColor: [\"rgb(0, 176, 204)\", \"rgb(255, 0, 0)\"],\n"
                            + "                            borderWidth: 3,\n"
                            + "                            data: [" + asistidosMarzo + ", " + faltadosMarzo + ", 0, " + totalMarzo + ", " + totalEnero + "]\n"
                            + "                        }\n"
                            + "                    ]\n"
                            + "                },\n"
                            + "                options: {\n"
                            + "                }\n"
                            + "            });";
                }
                if (mes > Calendar.MARCH) {
                    ArrayList<Object> datosAbril = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(4)));
                    infoAbril = (String) datosAbril.get(0);
                    totalAbril = (int) datosAbril.get(1);
                    asistidosAbril = (int) datosAbril.get(2);
                    faltadosAbril = (int) datosAbril.get(3);
                    htmlFinal += "<div class=\"mdl-cell mdl-cell--6-col\">\n"
                            + "                        <div class=\"tarjetas\" style=\"overflow: auto;\">\n"
                            + "                            <div class=\"descripcion graf\" style=\"\">\n"
                            + "                                <canvas id=\"" + Calendar.APRIL + "\" class=\"grafica\"></canvas>\n"
                            + "                            </div>\n"
                            + "                        </div>\n"
                            + "                    </div>\n"
                            + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                            + "                        <div class=\"tarjetas tamanoMes\" style=\"\">\n"
                            + "                            <div class=\"descripcion ajusta\" style=\"\">\n"
                            + "                                <div style=\"background-color: red;\" class=\"tituloMes\"><br>Abril</div>\n"
                            + "                                <div style=\"\" class=\"ajustarTabla\">\n"
                            + " " + infoAbril + "\n"
                            + "                                </div>\n"
                            + "                            </div>\n"
                            + "                        </div>\n"
                            + "                    </div>";
                    //Script para las graficas
                    scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'line',\n"
                            + "\n"
                            + "                // The data for our dataset\n"
                            + "                data: {\n"
                            + "                    labels: [\"Meses\", \"Enero\", \"Febrero\", \"Marzo\", \"Abril\"],\n"
                            + "                    datasets: [{\n"
                            + "                            label: \"Días Asistidos\",\n"
                            + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                            + "                            borderColor: 'rgb(255, 80, 0)',\n"
                            + "                            data: [0, " + asistidosEnero + ", " + asistidosFebrero + ", " + asistidosMarzo + ", " + asistidosAbril + ", " + totalEnero + "],\n"
                            + "                        }]\n"
                            + "                },\n"
                            + "\n"
                            + "                // Configuration options go here\n"
                            + "                options: {}\n"
                            + "            });\n"
                            + "\n";
                    scriptFinal += " \n"
                            + "            var ctx = document.getElementById('" + Calendar.APRIL + "').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'bar',\n"
                            + "                data: {\n"
                            + "                    labels: [\"Asistidos\", \"No Asistidos\"],\n"
                            + "                    datasets: [\n"
                            + "                        {\n"
                            + "                            label: \"Días\",\n"
                            + "                            backgroundColor: [\"rgba(0, 176, 204, 0.2)\", \"rgba(255, 0, 0, 0.2)\"],\n"
                            + "                            borderColor: [\"rgb(0, 176, 204)\", \"rgb(255, 0, 0)\"],\n"
                            + "                            borderWidth: 3,\n"
                            + "                            data: [" + asistidosAbril + ", " + faltadosAbril + ", 0, " + totalAbril + "]\n"
                            + "                        }\n"
                            + "                    ]\n"
                            + "                },\n"
                            + "                options: {\n"
                            + "                }\n"
                            + "            });";
                }
                if (mes > Calendar.APRIL) {
                    ArrayList<Object> datosMayo = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(5)));
                    infoMayo = (String) datosMayo.get(0);
                    totalMayo = (int) datosMayo.get(1);
                    asistidosMayo = (int) datosMayo.get(2);
                    faltadosMayo = (int) datosMayo.get(3);
                    htmlFinal += "<div class=\"mdl-cell mdl-cell--6-col\">\n"
                            + "                        <div class=\"tarjetas\" style=\"overflow: auto;\">\n"
                            + "                            <div class=\"descripcion graf\" style=\"\">\n"
                            + "                                <canvas id=\"" + Calendar.MAY + "\" class=\"grafica\"></canvas>\n"
                            + "                            </div>\n"
                            + "                        </div>\n"
                            + "                    </div>\n"
                            + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                            + "                        <div class=\"tarjetas tamanoMes\" style=\"\">\n"
                            + "                            <div class=\"descripcion ajusta\" style=\"\">\n"
                            + "                                <div style=\"background-color: red;\" class=\"tituloMes\"><br>Mayo</div>\n"
                            + "                                <div style=\"\" class=\"ajustarTabla\">\n"
                            + " " + infoMayo + "\n"
                            + "                                </div>\n"
                            + "                            </div>\n"
                            + "                        </div>\n"
                            + "                    </div>";
                    //Script para las graficas
                    scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'line',\n"
                            + "\n"
                            + "                // The data for our dataset\n"
                            + "                data: {\n"
                            + "                    labels: [\"Meses\", \"Enero\", \"Febrero\", \"Marzo\", \"Abril\", \"Mayo\"],\n"
                            + "                    datasets: [{\n"
                            + "                            label: \"Días Asistidos\",\n"
                            + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                            + "                            borderColor: 'rgb(255, 80, 0)',\n"
                            + "                            data: [0, " + asistidosEnero + ", " + asistidosFebrero + ", " + asistidosMarzo + ", " + asistidosAbril + ", " + asistidosMayo + ", " + totalEnero + "],\n"
                            + "                        }]\n"
                            + "                },\n"
                            + "\n"
                            + "                // Configuration options go here\n"
                            + "                options: {}\n"
                            + "            });\n"
                            + "\n";
                    scriptFinal += " \n"
                            + "            var ctx = document.getElementById('" + Calendar.MAY + "').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'bar',\n"
                            + "                data: {\n"
                            + "                    labels: [\"Asistidos\", \"No Asistidos\"],\n"
                            + "                    datasets: [\n"
                            + "                        {\n"
                            + "                            label: \"Días\",\n"
                            + "                            backgroundColor: [\"rgba(0, 176, 204, 0.2)\", \"rgba(255, 0, 0, 0.2)\"],\n"
                            + "                            borderColor: [\"rgb(0, 176, 204)\", \"rgb(255, 0, 0)\"],\n"
                            + "                            borderWidth: 3,\n"
                            + "                            data: [" + asistidosMayo + ", " + faltadosMayo + ", 0, " + totalMayo + "]\n"
                            + "                        }\n"
                            + "                    ]\n"
                            + "                },\n"
                            + "                options: {\n"
                            + "                }\n"
                            + "            });";
                }
                if (mes > Calendar.MAY) {
                    ArrayList<Object> datosJunio = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(5)));
                    infoJunio = (String) datosJunio.get(0);
                    totalJunio = (int) datosJunio.get(1);
                    asistidosJunio = (int) datosJunio.get(2);
                    faltadosJunio = (int) datosJunio.get(3);
                    htmlFinal += "<div class=\"mdl-cell mdl-cell--6-col\">\n"
                            + "                        <div class=\"tarjetas\" style=\"overflow: auto;\">\n"
                            + "                            <div class=\"descripcion graf\" style=\"\">\n"
                            + "                                <canvas id=\"" + Calendar.JUNE + "\" class=\"grafica\"></canvas>\n"
                            + "                            </div>\n"
                            + "                        </div>\n"
                            + "                    </div>\n"
                            + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                            + "                        <div class=\"tarjetas tamanoMes\" style=\"\">\n"
                            + "                            <div class=\"descripcion ajusta\" style=\"\">\n"
                            + "                                <div style=\"background-color: red;\" class=\"tituloMes\"><br>Junio</div>\n"
                            + "                                <div style=\"\" class=\"ajustarTabla\">\n"
                            + " " + infoJunio + "\n"
                            + "                                </div>\n"
                            + "                            </div>\n"
                            + "                        </div>\n"
                            + "                    </div>";
                    //Script para las graficas
                    scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'line',\n"
                            + "\n"
                            + "                // The data for our dataset\n"
                            + "                data: {\n"
                            + "                    labels: [\"Meses\", \"Enero\", \"Febrero\", \"Marzo\", \"Abril\", \"Mayo\", \"Junio\"],\n"
                            + "                    datasets: [{\n"
                            + "                            label: \"Días Asistidos\",\n"
                            + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                            + "                            borderColor: 'rgb(255, 80, 0)',\n"
                            + "                            data: [0, " + asistidosEnero + ", " + asistidosFebrero + ", " + asistidosMarzo + ", " + asistidosAbril + ", " + asistidosMayo + ", " + asistidosJunio + ", " + totalEnero + "],\n"
                            + "                        }]\n"
                            + "                },\n"
                            + "\n"
                            + "                // Configuration options go here\n"
                            + "                options: {}\n"
                            + "            });\n"
                            + "\n";
                    scriptFinal += " \n"
                            + "            var ctx = document.getElementById('" + Calendar.JUNE + "').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'bar',\n"
                            + "                data: {\n"
                            + "                    labels: [\"Asistidos\", \"No Asistidos\"],\n"
                            + "                    datasets: [\n"
                            + "                        {\n"
                            + "                            label: \"Días\",\n"
                            + "                            backgroundColor: [\"rgba(0, 176, 204, 0.2)\", \"rgba(255, 0, 0, 0.2)\"],\n"
                            + "                            borderColor: [\"rgb(0, 176, 204)\", \"rgb(255, 0, 0)\"],\n"
                            + "                            borderWidth: 3,\n"
                            + "                            data: [" + asistidosJunio + ", " + faltadosJunio + ", 0, " + totalJunio + "]\n"
                            + "                        }\n"
                            + "                    ]\n"
                            + "                },\n"
                            + "                options: {\n"
                            + "                }\n"
                            + "            });";
                }
                if (mes > Calendar.JUNE) {
                    ArrayList<Object> datosJulio = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(6)));
                    infoJulio = (String) datosJulio.get(0);
                    totalJulio = (int) datosJulio.get(1);
                    asistidosJulio = (int) datosJulio.get(2);
                    faltadosJulio = (int) datosJulio.get(3);
                    htmlFinal += "<div class=\"mdl-cell mdl-cell--6-col\">\n"
                            + "                        <div class=\"tarjetas\" style=\"overflow: auto;\">\n"
                            + "                            <div class=\"descripcion graf\" style=\"\">\n"
                            + "                                <canvas id=\"" + Calendar.JULY + "\" class=\"grafica\"></canvas>\n"
                            + "                            </div>\n"
                            + "                        </div>\n"
                            + "                    </div>\n"
                            + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                            + "                        <div class=\"tarjetas tamanoMes\" style=\"\">\n"
                            + "                            <div class=\"descripcion ajusta\" style=\"\">\n"
                            + "                                <div style=\"background-color: red;\" class=\"tituloMes\"><br>Julio</div>\n"
                            + "                                <div style=\"\" class=\"ajustarTabla\">\n"
                            + " " + infoJulio + "\n"
                            + "                                </div>\n"
                            + "                            </div>\n"
                            + "                        </div>\n"
                            + "                    </div>";
                    //Script para las graficas
                    scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'line',\n"
                            + "\n"
                            + "                // The data for our dataset\n"
                            + "                data: {\n"
                            + "                    labels: [\"Meses\", \"Enero\", \"Febrero\", \"Marzo\", \"Abril\", \"Mayo\", \"Junio\", \"Julio\"],\n"
                            + "                    datasets: [{\n"
                            + "                            label: \"Días Asistidos\",\n"
                            + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                            + "                            borderColor: 'rgb(255, 80, 0)',\n"
                            + "                            data: [0, " + asistidosEnero + ", " + asistidosFebrero + ", " + asistidosMarzo + ", " + asistidosAbril + ", " + asistidosMayo + ", " + asistidosJunio + "," + asistidosJulio + ", " + totalEnero + "],\n"
                            + "                        }]\n"
                            + "                },\n"
                            + "\n"
                            + "                // Configuration options go here\n"
                            + "                options: {}\n"
                            + "            });\n"
                            + "\n";
                    scriptFinal += " \n"
                            + "            var ctx = document.getElementById('" + Calendar.JULY + "').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'bar',\n"
                            + "                data: {\n"
                            + "                    labels: [\"Asistidos\", \"No Asistidos\"],\n"
                            + "                    datasets: [\n"
                            + "                        {\n"
                            + "                            label: \"Días\",\n"
                            + "                            backgroundColor: [\"rgba(0, 176, 204, 0.2)\", \"rgba(255, 0, 0, 0.2)\"],\n"
                            + "                            borderColor: [\"rgb(0, 176, 204)\", \"rgb(255, 0, 0)\"],\n"
                            + "                            borderWidth: 3,\n"
                            + "                            data: [" + asistidosJulio + ", " + faltadosJulio + ", 0, " + totalJulio + "]\n"
                            + "                        }\n"
                            + "                    ]\n"
                            + "                },\n"
                            + "                options: {\n"
                            + "                }\n"
                            + "            });";
                }
            }
        }
        _asistenciaIndividual = "<!DOCTYPE html>\n"
                + "<html>\n"
                + "    <head>\n"
                + "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                + "        <meta name=\"description\" content=\"PoliAsistencia\">\n"
                + "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0\">\n"
                + "        <title>Asistencia Individual</title>\n"
                + "        <link href=\"../css/mdl/material.css\" rel=\"stylesheet\" type=\"text/css\"/>\n"
                + "        <script src=\"../css/mdl/material.js\" type=\"text/javascript\"></script>\n"
                + "        <link href=\"../css/mdl/material.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n"
                + "        <script src=\"../css/mdl/material.min.js\" type=\"text/javascript\"></script>\n"
                + "        <link rel=\"shortcut icon\" href=\"../imagenes/iconos/poliAsistIcono.ico\" />\n"
                + "        <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\n"
                + "        <meta name=\"theme-color\" content=\"#00B0FF\" />\n"
                + "        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js\"></script>\n"
                + "        <meta name=\"theme-color\" content=\"#00B0FF\" />\n"
                + "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "        <meta name=\"HandheldFriendly\" content=\"true\">\n"
                + "        <style>\n"
                + "@font-face{\n"
                + "                font-family: Calibri;\n"
                + "                src: URL(\"../fuentes/calibri.ttf\") format(\"opentype\");\n"
                + "            }"
                + "            .titulo{\n"
                + "                font-size: 35px;\n"
                + "                color: #00B0FF;\n"
                + "                font-family: Calibri;\n"
                + "                padding-top: 30px;\n"
                + "            }\n"
                + "            .tituloBold{\n"
                + "                font-size: 40px;\n"
                + "                color: #0091EA;\n"
                + "                font-weight: bold;\n"
                + "                font-family: Calibri;\n"
                + "                padding-top: 30px;\n"
                + "            }\n"
                + "            .titulob{\n"
                + "                font-size: 35px;\n"
                + "                color: white;\n"
                + "                font-family: Calibri;\n"
                + "                padding-top: 33px;\n"
                + "            }\n"
                + "            .tituloBoldb{\n"
                + "                font-size: 40px;\n"
                + "                color: white;\n"
                + "                font-weight: bold;\n"
                + "                font-family: Calibri;\n"
                + "                padding-top: 33px;\n"
                + "            }\n"
                + "            #tarjeta{\n"
                + "                background-color: rgba(250, 250, 250, 0.4);\n"
                + "                text-align: left;\n"
                + "                color: white;\n"
                + "                font-size: 30px;\n"
                + "                width: auto;\n"
                + "                height: 30px;\n"
                + "                position: relative;\n"
                + "                border-radius: 5px;\n"
                + "                padding-top: 5px;\n"
                + "                font-family: Calibri; \n"
                + "            }\n"
                + "            .centrado{\n"
                + "                position: absolute;\n"
                + "                width: auto;\n"
                + "                height: auto;\n"
                + "                padding-left: 35%;\n"
                + "            }\n"
                + "            .persona{\n"
                + "                background-color: rgba(250, 250, 250, 0.0);\n"
                + "                color: white;\n"
                + "                font-size: 20px;\n"
                + "                border: 2px solid rgba(250, 250, 250, 0.0);\n"
                + "                width: auto;\n"
                + "            }\n"
                + "            #cuenta, #salir{\n"
                + "                display: none;\n"
                + "            }\n"
                + "            #barrita{\n"
                + "                background-color: white;\n"
                + "                height: 100%;\n"
                + "                width: 100%;\n"
                + "                position: fixed;\n"
                + "                -webkit-transition: all 1s ease;\n"
                + "                -o-transition: all 1s ease;\n"
                + "                transition: all 1s ease;\n"
                + "                z-index: 10000;\n"
                + "\n"
                + "            }\n"
                + "            #cargar{\n"
                + "                position: absolute;\n"
                + "                top: 0;\n"
                + "                left: 0;\n"
                + "                right: 0;\n"
                + "                bottom: 0;\n"
                + "                margin: auto;\n"
                + "            }\n"
                + "            .demo-card-wide.mdl-card {\n"
                + "                width: 700px;\n"
                + "            }\n"
                + "            .demo-card-wide > .mdl-card__title {\n"
                + "                color: #fff;\n"
                + "                height: auto;\n"
                + "                background-color: black;\n"
                + "            }\n"
                + "            .demo-card-wide > .mdl-card__menu {\n"
                + "                color: #fff;\n"
                + "            }\n"
                + "            .notificacion{\n"
                + "                padding-top: 15px;\n"
                + "                padding-bottom: 15px;\n"
                + "            }\n"
                + "            .adaptador{\n"
                + "                width: 1000px; padding-top: 30px; padding-bottom: 5px;\n"
                + "            }\n"
                + "\n"
                + "            /* Rules for sizing the icon. */\n"
                + "            .material-icons.md-18 { font-size: 18px; }\n"
                + "            .material-icons.md-24 { font-size: 24px; }\n"
                + "            .material-icons.md-36 { font-size: 26px; }\n"
                + "            .material-icons.md-48 { font-size: 54px; }\n"
                + "\n"
                + "            /* Rules for using icons as black on a light background. */\n"
                + "            .material-icons.md-dark { color: rgba(0, 0, 0, 0.54); }\n"
                + "            .material-icons.md-dark.md-inactive { color: rgba(0, 0, 0, 0.26); }\n"
                + "\n"
                + "            /* Rules for using icons as white on a dark background. */\n"
                + "            .material-icons.md-light { color: rgba(255, 255, 255, 1); }\n"
                + "            .material-icons.md-light.md-inactive { color: rgba(255, 255, 255, 0.3); }\n"
                + "\n"
                + "            .seleccionado{\n"
                + "                background: linear-gradient(to right, rgb(0, 145, 234), rgb(0, 158, 255));\n"
                + "                color: white !important;\n"
                + "                font-size: 20px;\n"
                + "\n"
                + "            }\n"
                + "            .disponible{\n"
                + "                font-size: 20px;\n"
                + "                transition: all 0.3s;\n"
                + "            }\n"
                + "            .tarjetas{\n"
                + "                background-color: white;\n"
                + "                width: auto;\n"
                + "                transition: all 0.3s cubic-bezier(.25,.8,.25,1);\n"
                + "                box-shadow: 0 1px 2px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);\n"
                + "                border-radius: 10px 15px;\n"
                + "                text-decoration: none;               \n"
                + "                height: auto;\n"
                + "                overflow: hidden;\n"
                + "            }\n"
                + "            a{\n"
                + "                text-decoration: none;\n"
                + "                color: inherit;\n"
                + "            }\n"
                + "            .tarjetas:hover{\n"
                + "                box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);\n"
                + "            }\n"
                + "            .mdl-grid.center-items {\n"
                + "                justify-content: center;\n"
                + "            }\n"
                + "            .grafica{\n"
                + "                width: 40%;\n"
                + "            }\n"
                + "            .iconos{\n"
                + "                width: 30%; height: inherit; position: relative; float: left; border-top-left-radius: 10px; border-bottom-left-radius: 15px;\n"
                + "                display: flex; justify-content: center; align-content: center; flex-direction: column; text-align: center;\n"
                + "            }\n"
                + "            .descripcion{\n"
                + "                width: 70%; height: inherit; position: relative; float: left; color: gray;\n"
                + "                font-size: 20px; display: flex; justify-content: center; align-content: center; flex-direction: column; text-align: center;\n"
                + "            }\n"
                + "            tbody{\n"
                + "\n"
                + "            }\n"
                + "            .titulos{\n"
                + "                color: rgb(255, 80, 0); font-size: 50px; padding-top: 30px; padding-bottom: 20px;\n"
                + "            }\n"
                + "            .graf{\n"
                + "                width: 90%; left: 5%;\n"
                + "            }\n"
                + "            .tamanoMes{\n"
                + "                height: 294px;\n"
                + "            }\n"
                + "            .ajusta{\n"
                + "                width: 100%;  height: auto;\n"
                + "            }\n"
                + "            .tituloMes{\n"
                + "                color: white; font-size: 34px; text-align: center; width: 100%; height: 54px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);\n"
                + "            }\n"
                + "            .ajustarTabla{\n"
                + "                width: 100%; height: 240px; overflow: auto;\n"
                + "            }\n"
                + "\n"
                + "\n"
                +"@media screen and (max-width: 479px){\n"
                + "                .mdl-grid{\n"
                + "\n"
                + "                }\n"
                + "            }\n"
                + "            @media screen and (max-width: 500px){\n"
                + "                \n"
                + "                .titulob{\n"
                + "                    font-size: 35px;\n"
                + "                    color: transparent;\n"
                + "                    font-family: Calibri;\n"
                + "                    padding-top: 33px;\n"
                + "                }\n"
                + "                .tituloBoldb{\n"
                + "                    font-size: 40px;\n"
                + "                    color: transparent;\n"
                + "                    font-weight: bold;\n"
                + "                    font-family: Calibri;\n"
                + "                    padding-top: 33px;\n"
                + "                }\n"
                + "                .notificacion{\n"
                + "                    padding-left: 5px;\n"
                + "                    padding-right: 5px;\n"
                + "                }\n"
                + "                .editor{\n"
                + "                    width: 100%;\n"
                + "                }\n"
                + "                .notificacionEditor{\n"
                + "                    margin-top: auto; margin-left: auto; width: 90%; left: 10%;\n"
                + "                }\n"
                + "                .mdl-grid{\n"
                + "\n"
                + "                }\n"
                + "                .adapGrafica{\n"
                + "                    width: 100%; left: 0%;\n"
                + "                }\n"
                + "                .adapTarjetaGrafica{\n"
                + "                    height: auto;\n"
                + "                    overflow: hidden;\n"
                + "                }\n"
                + "                .titGrafica{\n"
                + "                    font-size: 22px;\n"
                + "                }\n"
                + "                .subGrafica{\n"
                + "                    font-size: 33px; \n"
                + "                }\n"
                + "                .titHorario{\n"
                + "                    font-size: 20px\n"
                + "                }\n"
                + "                .titOtro{\n"
                + "                    font-size: 20px;\n"
                + "                }\n"
                + "                .subOtro{\n"
                + "                    font-size: 15px;\n"
                + "                }\n"
                + ".titulos{font-size: 37px;}"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "            }\n"
                + "            @media screen and (max-width: 839px){\n"
                + "                .adapGrafica{\n"
                + "                    width: 90%; left: 5%;\n"
                + "                }\n"
                + "                .adapTarjetaGrafica{\n"
                + "                    height: auto;\n"
                + "                    overflow: hidden;\n"
                + "                }\n"
                + "                .titGrafica{\n"
                + "                    font-size: 28px;\n"
                + "                }\n"
                + "                .subGrafica{\n"
                + "                    font-size: 40px; \n"
                + "                }\n"
                + "                .tarjetaPequena{\n"
                + "                    height: auto;\n"
                + "                    overflow: hidden;\n"
                + "                }\n"
                + "                .tarjetas{\n"
                + "                    box-shadow: none;\n"
                + "                    border-radius: initial;\n"
                + "                    transform: none;\n"
                + "                    \n"
                + "                }\n"
                + "                .tarjetas:hover{\n"
                + "                    box-shadow: none;\n"
                + "                }\n"
                + "                .iconos{\n"
                + "                    border-radius: initial;\n"
                + "                }\n"
                + "            }\n"
                + "\n"
                + "            @media screen and (max-width: 1024px){\n"
                + "                .titulob{\n"
                + "                    font-size: 0px;\n"
                + "                    position: absolute;\n"
                + "                    float: right;\n"
                + "                }\n"
                + "                .tituloBoldb{\n"
                + "                    font-size: 0px;\n"
                + "                    position: absolute;\n"
                + "                    float: right;\n"
                + "                }\n"
                + "                #cuenta, #salir{\n"
                + "                    display: block;\n"
                + "                }\n"
                + "                .notificacion{\n"
                + "                    padding-left: 50px;\n"
                + "                    padding-right: 50px;\n"
                + "                }\n"
                + "                .editor{\n"
                + "\n"
                + "                }\n"
                + "                .notificacionEditor{\n"
                + "                    padding-left: 50px;\n"
                + "                    padding-right: 50px;\n"
                + "                }\n"
                + "\n"
                + "                body {\n"
                + "                    font-size: calc(0.75em + 1vmin);\n"
                + "                }\n"
                + "                .titGrafica{\n"
                + "                    font-size: 28px;\n"
                + "                }\n"
                + "                .subGrafica{\n"
                + "                    font-size: 50px; \n"
                + "                }\n"
                + "\n"
                + "\n"
                + "            }"
                + "        </style>\n"
                + "\n"
                + "\n"
                + "        <script>\n"
                + "            window.onload = function () {\n"
                + "                var barrita = document.getElementById('barrita');\n"
                + "                barrita.style.visibility = 'hidden';\n"
                + "                barrita.style.opacity = '0';\n"
                + "            }\n"
                + "        </script>\n"
                + "\n"
                + "    </head>\n"
                + "    <body>\n"
                + "        <div id=\"barrita\">\n"
                + "            <div id=\"cargar\" class=\"mdl-progress mdl-js-progress mdl-progress__indeterminate\"><br><center><span class=\"titulo\">Cargando...</span></center></div> \n"
                + "        </div>\n"
                + "        <!-- Always shows a header, even in smaller screens. -->\n"
                + "        <div class=\"mdl-layout mdl-js-layout mdl-layout--fixed-header\">\n"
                + "            <header class=\"mdl-layout__header\" style=\"background-color: transparent;\">\n"
                + "                <div class=\"mdl-layout__header-row\" style=\"background: linear-gradient(to right, #0091EA, #00D4FF);\">\n"
                + "                    <!-- Title -->\n"
                + "                    <div id=\"tarjeta\">&nbsp;Estadísticas&nbsp;</div><div class=\"centrado\"><span class=\"titulob\">&nbsp;Poli<span class=\"tituloBoldb\">Asistencia</span></span></div>\n"
                + "                    <!-- Add spacer, to align navigation to the right -->\n"
                + "                    <div class=\"mdl-layout-spacer\"></div>\n"
                + "\n"
                + "                    <!-- Navigation. We hide it in small screens. -->\n"
                + "                    <nav class=\"mdl-navigation mdl-layout--large-screen-only\">\n"
                + "                        <button id=\"demo-menu-lower-right\"\n"
                + "                                class=\"persona\">\n"
                + "                            " + _nombre + "\n"
                + "                        </button>\n"
                + "                        <ul class=\"mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect\"\n"
                + "                            for=\"demo-menu-lower-right\">\n"
                + "                            <a href=\"../configuracion\"><li class=\"mdl-menu__item\">Configuración de la cuenta</li></a>\n"
                + "                            <a href=\"../cerrarSesion\"><li class=\"mdl-menu__item\">Cerrar Sesión</li></a>\n"
                + "                        </ul>\n"
                + "                    </nav>\n"
                + "                </div>\n"
                + "            </header>\n"
                + "            <div class=\"mdl-layout__drawer\">\n"
                + "                <span class=\"titulo\">&nbsp;Poli<span class=\"tituloBold\">Asistencia</span></span>\n"
                + "                <nav class=\"mdl-navigation\">\n"
                + "                    <a class=\"mdl-navigation__link disponible\" href=\"../inicio\"><i class=\"material-icons md-36 md-dark\">home</i> Inicio</a>\n"
                + "                    <a class=\"mdl-navigation__link disponible\" href=\"../horario\" ><i class=\"material-icons md-36 md-dark\">date_range</i> Horario</a>\n"
                + "                    <a class=\"mdl-navigation__link seleccionado\" href=\"../estadisticas\"><i class=\"material-icons md-36 md-light\">insert_chart</i> Estadisticas</a>\n"
                + "                    <a class=\"mdl-navigation__link disponible\" href=\"../notificaciones\"><i class=\"material-icons md-36 md-dark\">list</i> Notificaciones</a>\n"
                + "                    <a class=\"mdl-navigation__link disponible\" href=\"../configuracion\"><i class=\"material-icons md-36 md-dark\">settings</i> Configuración</a>\n"
                + "                    <a class=\"mdl-navigation__link disponible\" href=\"../cerrarSesion\"><i class=\"material-icons md-36 md-dark\">exit_to_app</i> Cerrar Sesión</a>\n"
                + "\n"
                + "                </nav>\n"
                + "            </div>\n"
                + "            <main class=\"mdl-layout__content\" style=\"background-color: whitesmoke;\">\n"
                + "                <div class=\"mdl-grid center-items\">\n"
                + "                    <span style=\"\" class=\"titulos\">Asistencia Individual</span>\n"
                + "                    <div class=\"mdl-cell mdl-cell--10-col\">\n"
                + "                        <div class=\"tarjetas\" style=\"\">\n"
                + "                            <div class=\"descripcion graf\" style=\"\">\n"
                + "\n"
                + "                                <canvas id=\"grafica\" class=\"grafica\"></canvas>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                    `" + htmlFinal + " \n"
                + "                </div>\n"
                + "\n"
                + "\n"
                + "            </main>\n"
                + "        </div>\n"
                + "        <script>\n"
                + "            " + scriptGeneral + " \n"
                + "            " + scriptFinal + " \n"
                + "        </script>\n"
                + "    </body>\n"
                + "</html>\n"
                + "";
        return _asistenciaIndividual;
    }

    private static java.util.List<java.lang.Object> asistenciaInd(java.lang.String idPer, java.lang.String mes) {
        serviciosWebJefeAcademia.JefeAcademia_Service service = new serviciosWebJefeAcademia.JefeAcademia_Service();
        serviciosWebJefeAcademia.JefeAcademia port = service.getJefeAcademiaPort();
        return port.asistenciaInd(idPer, mes);
    }
}
