/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package profesor;

import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 *
 * @author Caleb
 */
public class inicio {

    private int _idPersona = 0;
    private int _idTipo = 0;
    private String _numero = "";
    private String _nombre = "";
    private String _inicio = "";

    public inicio(int idPersona, int idTipo, String numero, String nombre) {
        _idPersona = idPersona;
        _idTipo = idTipo;
        _numero = numero;
        _nombre = nombre;
    }

    public String dibujarInicio() {
        String scriptGeneral = "";
        //Ciclo 1
        int asistidosAgosto = 0, totalAgosto = 0;
        int asistidosSeptiembre = 0;
        int asistidosOctubre = 0;
        int asistidosNoviembre = 0;
        int asistidosDiciembre = 0;

        //Ciclo 2
        int asistidosEnero = 0, totalEnero = 0;
        int asistidosFebrero = 0;
        int asistidosMarzo = 0;
        int asistidosAbril = 0;
        int asistidosMayo = 0;
        int asistidosJunio = 0;
        int asistidosJulio = 0;

        int diasTotal = 0;

        //Necesarios para obtener informacion
        Calendar calendario = new GregorianCalendar();
        int mes = calendario.get(Calendar.MONTH);
        if (mes > Calendar.JULY && mes < Calendar.DECEMBER + 1) {//Ciclo 1
            if (mes > Calendar.JULY) {
                ArrayList<Object> datosAgosto = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(8)));
                totalAgosto = (int) datosAgosto.get(1);
                asistidosAgosto = (int) datosAgosto.get(2);
                scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'line',\n"
                        + "\n"
                        + "                // The data for our dataset\n"
                        + "                data: {\n"
                        + "                    labels: [\"Meses\", \"Agosto\"],\n"
                        + "                    datasets: [{\n"
                        + "                            label: \"Días Asistidos\",\n"
                        + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                        + "                            borderColor: 'rgb(255, 80, 0)',\n"
                        + "                            data: [0, " + asistidosAgosto + ", " + totalAgosto + "],\n"
                        + "                        }]\n"
                        + "                },\n"
                        + "\n"
                        + "                // Configuration options go here\n"
                        + "                options: {}\n"
                        + "            });\n"
                        + "\n";
                diasTotal = asistidosAgosto;
            }
            if (mes > Calendar.AUGUST) {
                ArrayList<Object> datosSeptiembre = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(9)));
                asistidosSeptiembre = (int) datosSeptiembre.get(2);

                scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'line',\n"
                        + "\n"
                        + "                // The data for our dataset\n"
                        + "                data: {\n"
                        + "                    labels: [\"Meses\", \"Agosto\", \"Septiembre\"],\n"
                        + "                    datasets: [{\n"
                        + "                            label: \"Días Asistidos\",\n"
                        + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                        + "                            borderColor: 'rgb(255, 80, 0)',\n"
                        + "                            data: [0, " + asistidosAgosto + ", " + asistidosSeptiembre + ", " + totalAgosto + "],\n"
                        + "                        }]\n"
                        + "                },\n"
                        + "\n"
                        + "                // Configuration options go here\n"
                        + "                options: {}\n"
                        + "            });\n"
                        + "\n";
                diasTotal = asistidosAgosto + asistidosSeptiembre;
            }
            if (mes > Calendar.SEPTEMBER) {
                ArrayList<Object> datosOctubre = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(10)));
                asistidosOctubre = (int) datosOctubre.get(2);
                scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'line',\n"
                        + "\n"
                        + "                // The data for our dataset\n"
                        + "                data: {\n"
                        + "                    labels: [\"Meses\", \"Agosto\", \"Septiembre\", \"Octubre\"],\n"
                        + "                    datasets: [{\n"
                        + "                            label: \"Días Asistidos\",\n"
                        + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                        + "                            borderColor: 'rgb(255, 80, 0)',\n"
                        + "                            data: [0, " + asistidosAgosto + ", " + asistidosSeptiembre + ", " + asistidosOctubre + ", " + totalAgosto + "],\n"
                        + "                        }]\n"
                        + "                },\n"
                        + "\n"
                        + "                // Configuration options go here\n"
                        + "                options: {}\n"
                        + "            });\n"
                        + "\n";
                diasTotal = asistidosAgosto + asistidosSeptiembre + asistidosOctubre;
            }
            if (mes > Calendar.OCTOBER) {
                ArrayList<Object> datosNoviembre = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(11)));
                asistidosNoviembre = (int) datosNoviembre.get(2);
                scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'line',\n"
                        + "\n"
                        + "                // The data for our dataset\n"
                        + "                data: {\n"
                        + "                    labels: [\"Meses\", \"Agosto\", \"Septiembre\", \"Octubre\", \"Noviembre\"],\n"
                        + "                    datasets: [{\n"
                        + "                            label: \"Días Asistidos\",\n"
                        + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                        + "                            borderColor: 'rgb(255, 80, 0)',\n"
                        + "                            data: [0, " + asistidosAgosto + ", " + asistidosSeptiembre + ", " + asistidosOctubre + ", " + asistidosNoviembre + ", " + totalAgosto + "],\n"
                        + "                        }]\n"
                        + "                },\n"
                        + "\n"
                        + "                // Configuration options go here\n"
                        + "                options: {}\n"
                        + "            });\n"
                        + "\n";
                diasTotal = asistidosAgosto + asistidosSeptiembre + asistidosOctubre + asistidosNoviembre;
            }
            if (mes > Calendar.NOVEMBER) {
                ArrayList<Object> datosDiciembre = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(12)));
                asistidosDiciembre = (int) datosDiciembre.get(2);
                scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                        + "            var chart = new Chart(ctx, {\n"
                        + "                // The type of chart we want to create\n"
                        + "                type: 'line',\n"
                        + "\n"
                        + "                // The data for our dataset\n"
                        + "                data: {\n"
                        + "                    labels: [\"Meses\", \"Agosto\", \"Septiembre\", \"Octubre\", \"Noviembre\", \"Diciembre\"],\n"
                        + "                    datasets: [{\n"
                        + "                            label: \"Días Asistidos\",\n"
                        + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                        + "                            borderColor: 'rgb(255, 80, 0)',\n"
                        + "                            data: [0, " + asistidosAgosto + ", " + asistidosSeptiembre + ", " + asistidosOctubre + ", " + asistidosNoviembre + ", " + asistidosDiciembre + ", " + totalAgosto + "],\n"
                        + "                        }]\n"
                        + "                },\n"
                        + "\n"
                        + "                // Configuration options go here\n"
                        + "                options: {}\n"
                        + "            });\n"
                        + "\n";
                diasTotal = asistidosAgosto + asistidosSeptiembre + asistidosOctubre + asistidosNoviembre + asistidosDiciembre;
            }
        } else {
            if (mes > Calendar.JANUARY-1 && mes < Calendar.AUGUST) {//Ciclo 2
                if (mes > Calendar.JANUARY-1) {
                    ArrayList<Object> datosEnero = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(1)));
                    totalEnero = (int) datosEnero.get(1);
                    asistidosEnero = (int) datosEnero.get(2);
                    scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'line',\n"
                            + "\n"
                            + "                // The data for our dataset\n"
                            + "                data: {\n"
                            + "                    labels: [\"Meses\", \"Enero\"],\n"
                            + "                    datasets: [{\n"
                            + "                            label: \"Días Asistidos\",\n"
                            + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                            + "                            borderColor: 'rgb(255, 80, 0)',\n"
                            + "                            data: [0, " + asistidosEnero + ", " + totalEnero + "],\n"
                            + "                        }]\n"
                            + "                },\n"
                            + "\n"
                            + "                // Configuration options go here\n"
                            + "                options: {}\n"
                            + "            });\n"
                            + "\n";
                    diasTotal = asistidosEnero;
                }
                if (mes > Calendar.JANUARY) {
                    ArrayList<Object> datosFebrero = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(2)));
                    asistidosFebrero = (int) datosFebrero.get(2);

                    scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'line',\n"
                            + "\n"
                            + "                // The data for our dataset\n"
                            + "                data: {\n"
                            + "                    labels: [\"Meses\", \"Enero\", \"Febrero\"],\n"
                            + "                    datasets: [{\n"
                            + "                            label: \"Días Asistidos\",\n"
                            + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                            + "                            borderColor: 'rgb(255, 80, 0)',\n"
                            + "                            data: [0, " + asistidosEnero + ", " + asistidosFebrero + ", " + totalEnero + "],\n"
                            + "                        }]\n"
                            + "                },\n"
                            + "\n"
                            + "                // Configuration options go here\n"
                            + "                options: {}\n"
                            + "            });\n"
                            + "\n";
                    diasTotal = asistidosEnero + asistidosFebrero;
                }
                if (mes > Calendar.FEBRUARY) {
                    ArrayList<Object> datosMarzo = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(3)));
                    asistidosMarzo = (int) datosMarzo.get(2);
                    scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'line',\n"
                            + "\n"
                            + "                // The data for our dataset\n"
                            + "                data: {\n"
                            + "                    labels: [\"Meses\", \"Enero\", \"Febrero\", \"Marzo\"],\n"
                            + "                    datasets: [{\n"
                            + "                            label: \"Días Asistidos\",\n"
                            + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                            + "                            borderColor: 'rgb(255, 80, 0)',\n"
                            + "                            data: [0, " + asistidosEnero + ", " + asistidosFebrero + ", " + asistidosMarzo + ", " + totalEnero + "],\n"
                            + "                        }]\n"
                            + "                },\n"
                            + "\n"
                            + "                // Configuration options go here\n"
                            + "                options: {}\n"
                            + "            });\n"
                            + "\n";
                    diasTotal = asistidosEnero + asistidosFebrero + asistidosMarzo;
                }
                if (mes > Calendar.MARCH) {
                    ArrayList<Object> datosAbril = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(4)));
                    asistidosAbril = (int) datosAbril.get(2);
                    scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'line',\n"
                            + "\n"
                            + "                // The data for our dataset\n"
                            + "                data: {\n"
                            + "                    labels: [\"Meses\", \"Enero\", \"Febrero\", \"Marzo\", \"Abril\"],\n"
                            + "                    datasets: [{\n"
                            + "                            label: \"Días Asistidos\",\n"
                            + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                            + "                            borderColor: 'rgb(255, 80, 0)',\n"
                            + "                            data: [0, " + asistidosEnero + ", " + asistidosFebrero + ", " + asistidosMarzo + ", " + asistidosAbril + ", " + totalEnero + "],\n"
                            + "                        }]\n"
                            + "                },\n"
                            + "\n"
                            + "                // Configuration options go here\n"
                            + "                options: {}\n"
                            + "            });\n"
                            + "\n";
                    diasTotal = asistidosEnero + asistidosFebrero + asistidosMarzo + asistidosAbril;
                }
                if (mes > Calendar.APRIL) {
                    ArrayList<Object> datosMayo = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(5)));
                    asistidosMayo = (int) datosMayo.get(2);
                    scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'line',\n"
                            + "\n"
                            + "                // The data for our dataset\n"
                            + "                data: {\n"
                            + "                    labels: [\"Meses\", \"Enero\", \"Febrero\", \"Marzo\", \"Abril\", \"Mayo\"],\n"
                            + "                    datasets: [{\n"
                            + "                            label: \"Días Asistidos\",\n"
                            + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                            + "                            borderColor: 'rgb(255, 80, 0)',\n"
                            + "                            data: [0, " + asistidosEnero + ", " + asistidosFebrero + ", " + asistidosMarzo + ", " + asistidosAbril + ", " + asistidosMayo + ", " + totalAgosto + "],\n"
                            + "                        }]\n"
                            + "                },\n"
                            + "\n"
                            + "                // Configuration options go here\n"
                            + "                options: {}\n"
                            + "            });\n"
                            + "\n";
                    diasTotal = asistidosEnero + asistidosFebrero + asistidosMarzo + asistidosAbril + asistidosMayo;
                }
                if (mes > Calendar.MAY) {
                    ArrayList<Object> datosJunio = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(6)));
                    asistidosJunio = (int) datosJunio.get(2);
                    scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'line',\n"
                            + "\n"
                            + "                // The data for our dataset\n"
                            + "                data: {\n"
                            + "                    labels: [\"Meses\", \"Enero\", \"Febrero\", \"Marzo\", \"Abril\", \"Mayo\", \"Junio\"],\n"
                            + "                    datasets: [{\n"
                            + "                            label: \"Días Asistidos\",\n"
                            + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                            + "                            borderColor: 'rgb(255, 80, 0)',\n"
                            + "                            data: [0, " + asistidosEnero + ", " + asistidosFebrero + ", " + asistidosMarzo + ", " + asistidosAbril + ", " + asistidosMayo + ", " + asistidosJunio + ", " + totalAgosto + "],\n"
                            + "                        }]\n"
                            + "                },\n"
                            + "\n"
                            + "                // Configuration options go here\n"
                            + "                options: {}\n"
                            + "            });\n"
                            + "\n";
                    diasTotal = asistidosEnero + asistidosFebrero + asistidosMarzo + asistidosAbril + asistidosMayo + asistidosJunio;
                }
                if (mes > Calendar.JUNE) {
                    ArrayList<Object> datosJulio = new ArrayList<>(asistenciaInd(Integer.toString(_idPersona), Integer.toString(7)));
                    asistidosJulio = (int) datosJulio.get(2);
                    scriptGeneral = "var ctx = document.getElementById('grafica').getContext('2d');\n"
                            + "            var chart = new Chart(ctx, {\n"
                            + "                // The type of chart we want to create\n"
                            + "                type: 'line',\n"
                            + "\n"
                            + "                // The data for our dataset\n"
                            + "                data: {\n"
                            + "                    labels: [\"Meses\", \"Enero\", \"Febrero\", \"Marzo\", \"Abril\", \"Mayo\", \"Junio\", \"Julio\"],\n"
                            + "                    datasets: [{\n"
                            + "                            label: \"Días Asistidos\",\n"
                            + "                            backgroundColor: 'rgba(255, 80, 0, 0.2)',\n"
                            + "                            borderColor: 'rgb(255, 80, 0)',\n"
                            + "                            data: [0, " + asistidosEnero + ", " + asistidosFebrero + ", " + asistidosMarzo + ", " + asistidosAbril + ", " + asistidosMayo + ", " + asistidosJunio + ", " + asistidosJulio + ", " + totalAgosto + "],\n"
                            + "                        }]\n"
                            + "                },\n"
                            + "\n"
                            + "                // Configuration options go here\n"
                            + "                options: {}\n"
                            + "            });\n"
                            + "\n";
                    diasTotal = asistidosEnero + asistidosFebrero + asistidosMarzo + asistidosAbril + asistidosMayo + asistidosJunio + asistidosJulio;
                }
            }
        }
        _inicio = "\n"
                + "<!DOCTYPE html>\n"
                + "<html>\n"
                + "    <head>\n"
                + "        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n"
                + "        <meta name=\"description\" content=\"PoliAsistencia\">\n"
                + "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0, minimum-scale=1.0\">\n"
                + "        <title>Inicio</title>\n"
                + "        <link href=\"css/mdl/material.css\" rel=\"stylesheet\" type=\"text/css\"/>\n"
                + "        <script src=\"css/mdl/material.js\" type=\"text/javascript\"></script>\n"
                + "        <link href=\"css/mdl/material.min.css\" rel=\"stylesheet\" type=\"text/css\"/>\n"
                + "        <script src=\"css/mdl/material.min.js\" type=\"text/javascript\"></script>\n"
                + "        <link rel=\"shortcut icon\" href=\"imagenes/iconos/poliAsistIcono.ico\" />\n"
                + "        <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\n"
                + "        <meta name=\"theme-color\" content=\"#00B0FF\" />\n"
                + "        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js\"></script>\n"
                + "        <meta name=\"theme-color\" content=\"#00B0FF\" />\n"
                + "        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
                + "        <meta name=\"HandheldFriendly\" content=\"true\">\n"
                + "        <style>\n"
                + "@font-face{\n"
                + "                font-family: Calibri;\n"
                + "                src: URL(\"fuentes/calibri.ttf\") format(\"opentype\");\n"
                + "            }"
                + "            .titulo{\n"
                + "                font-size: 35px;\n"
                + "                color: #00B0FF;\n"
                + "                font-family: Calibri;\n"
                + "                padding-top: 30px;\n"
                + "                margin-bottom: 10px;\n"
                + "            }\n"
                + "            .tituloBold{\n"
                + "                font-size: 40px;\n"
                + "                color: #0091EA;\n"
                + "                font-weight: bold;\n"
                + "                font-family: Calibri;\n"
                + "                padding-top: 30px;\n"
                + "            }\n"
                + "            .titulob{\n"
                + "                font-size: 35px;\n"
                + "                color: white;\n"
                + "                font-family: Calibri;\n"
                + "                padding-top: 33px;\n"
                + "            }\n"
                + "            .tituloBoldb{\n"
                + "                font-size: 40px;\n"
                + "                color: white;\n"
                + "                font-weight: bold;\n"
                + "                font-family: Calibri;\n"
                + "                padding-top: 33px;\n"
                + "            }\n"
                + "            #tarjeta{\n"
                + "                background-color: rgba(250, 250, 250, 0.4);\n"
                + "                text-align: left;\n"
                + "                color: white;\n"
                + "                font-size: 30px;\n"
                + "                width: auto;\n"
                + "                height: 30px;\n"
                + "                position: relative;\n"
                + "                border-radius: 5px;\n"
                + "                padding-top: 5px;\n"
                + "                font-family: Calibri;\n"
                + "\n"
                + "            }\n"
                + "            .centrado{\n"
                + "                position: absolute;\n"
                + "                width: auto;\n"
                + "                height: auto;\n"
                + "                padding-left: 35%;\n"
                + "            }\n"
                + "            .persona{\n"
                + "                background-color: rgba(250, 250, 250, 0.0);\n"
                + "                color: white;\n"
                + "                font-size: 20px;\n"
                + "                border: 2px solid rgba(250, 250, 250, 0.0);\n"
                + "                width: auto;\n"
                + "            }\n"
                + "            #cuenta, #salir{\n"
                + "                display: none;\n"
                + "            }\n"
                + "            #barrita{\n"
                + "                background-color: white;\n"
                + "                height: 100%;\n"
                + "                width: 100%;\n"
                + "                position: fixed;\n"
                + "                -webkit-transition: all 1s ease;\n"
                + "                -o-transition: all 1s ease;\n"
                + "                transition: all 1s ease;\n"
                + "                z-index: 10000;\n"
                + "\n"
                + "            }\n"
                + "            #cargar{\n"
                + "                position: absolute;\n"
                + "                top: 0;\n"
                + "                left: 0;\n"
                + "                right: 0;\n"
                + "                bottom: 0;\n"
                + "                margin: auto;\n"
                + "            }\n"
                + "            .demo-card-wide.mdl-card {\n"
                + "                width: 700px;\n"
                + "            }\n"
                + "            .demo-card-wide > .mdl-card__title {\n"
                + "                color: #fff;\n"
                + "                height: auto;\n"
                + "                background-color: black;\n"
                + "            }\n"
                + "            .demo-card-wide > .mdl-card__menu {\n"
                + "                color: #fff;\n"
                + "            }\n"
                + "            .notificacion{\n"
                + "                padding-top: 15px;\n"
                + "                padding-bottom: 15px;\n"
                + "            }\n"
                + "            .editor{\n"
                + "                background-color: #fff; width: 30%; height: auto; float: left; margin: 30px; box-shadow: 0 6px 20px 0 rgba(0, 0, 0, 0.19); overflow: scroll;\n"
                + "            }\n"
                + "            .notificacionEditor{\n"
                + "                margin-top: 70px; margin-left: 50px;\n"
                + "            }\n"
                + "            .mdl-textfield{\n"
                + "                width:70%;\n"
                + "            }\n"
                + "            /* Rules for sizing the icon. */\n"
                + "            .material-icons.md-18 { font-size: 18px; }\n"
                + "            .material-icons.md-24 { font-size: 24px; }\n"
                + "            .material-icons.md-36 { font-size: 26px; }\n"
                + "            .material-icons.md-48 { font-size: 54px; }\n"
                + "\n"
                + "            /* Rules for using icons as black on a light background. */\n"
                + "            .material-icons.md-dark { color: rgba(0, 0, 0, 0.54); }\n"
                + "            .material-icons.md-dark.md-inactive { color: rgba(0, 0, 0, 0.26); }\n"
                + "\n"
                + "            /* Rules for using icons as white on a dark background. */\n"
                + "            .material-icons.md-light { color: rgba(255, 255, 255, 1); }\n"
                + "            .material-icons.md-light.md-inactive { color: rgba(255, 255, 255, 0.3); }\n"
                + "\n"
                + "            .tarjetas{\n"
                + "                background-color: white;\n"
                + "                width: auto;\n"
                + "                transition: all 0.3s cubic-bezier(.25,.8,.25,1);\n"
                + "                box-shadow: 0 1px 2px rgba(0,0,0,0.12), 0 1px 2px rgba(0,0,0,0.24);\n"
                + "                border-radius: 10px 15px;\n"
                + "                text-decoration: none; \n"
                + "                height: 94px;\n"
                + "            }\n"
                + "            a{\n"
                + "                text-decoration: none;\n"
                + "                color: inherit;\n"
                + "            }\n"
                + "            .tarjetas:hover{\n"
                + "                box-shadow: 0 10px 20px rgba(0,0,0,0.19), 0 6px 6px rgba(0,0,0,0.23);\n"
                + "            }\n"
                + "            .mdl-grid.center-items {\n"
                + "                justify-content: center;\n"
                + "            }\n"
                + "            .iconos{\n"
                + "                width: 30%; height: inherit; position: relative; float: left; border-top-left-radius: 10px; border-bottom-left-radius: 15px;\n"
                + "                display: flex; justify-content: center; align-content: center; flex-direction: column; text-align: center;\n"
                + "            }\n"
                + "            .descripcion{\n"
                + "                width: 70%; height: inherit; position: relative; float: left; color: gray;\n"
                + "                font-size: 20px; display: flex; justify-content: center; align-content: center; flex-direction: column; text-align: center;\n"
                + "            }\n"
                + "            .seleccionado{\n"
                + "                background: linear-gradient(to right, rgb(0, 145, 234), rgb(0, 158, 255));\n"
                + "                color: white !important;\n"
                + "                font-size: 20px;\n"
                + "\n"
                + "            }\n"
                + "            .disponible{\n"
                + "                font-size: 20px;\n"
                + "                transition: all 0.3s;\n"
                + "            }\n"
                + "            .adapGrafica{\n"
                + "                width: 50%\n"
                + "            }\n"
                + "            .adapTarjetaGrafica{\n"
                + "                height: 400px;\n"
                + "            }\n"
                + "            .titGrafica{\n"
                + "                font-size: 37px; color: gray;\n"
                + "            }\n"
                + "            .subGrafica{\n"
                + "                font-size: 55px; color: rgb(240, 36, 0)\n"
                + "            }\n"
                + "            .ajustarTabla{\n"
                + "                width: 100%; height: 250px; overflow: auto;\n"
                + "            }\n"
                + "            .tarjetaPequena{\n"
                + "                height: 190px;\n"
                + "            }\n"
                + "            .titHorario{\n"
                + "                font-size: 30px; color: rgb(255, 166, 0)\n"
                + "            }\n"
                + "            .titOtro{\n"
                + "                    font-size: 27px;\n"
                + "                }\n"
                + "                .subOtro{\n"
                + "                    font-size: 20px;\n"
                + "                }\n"
+"@media screen and (max-width: 479px){\n"
                + "                .mdl-grid{\n"
                + "\n"
                + "                }\n"
                + "            }\n"
                + "            @media screen and (max-width: 500px){\n"
                + "                \n"
                + "                .titulob{\n"
                + "                    font-size: 35px;\n"
                + "                    color: transparent;\n"
                + "                    font-family: Calibri;\n"
                + "                    padding-top: 33px;\n"
                + "                }\n"
                + "                .tituloBoldb{\n"
                + "                    font-size: 40px;\n"
                + "                    color: transparent;\n"
                + "                    font-weight: bold;\n"
                + "                    font-family: Calibri;\n"
                + "                    padding-top: 33px;\n"
                + "                }\n"
                + "                .notificacion{\n"
                + "                    padding-left: 5px;\n"
                + "                    padding-right: 5px;\n"
                + "                }\n"
                + "                .editor{\n"
                + "                    width: 100%;\n"
                + "                }\n"
                + "                .notificacionEditor{\n"
                + "                    margin-top: auto; margin-left: auto; width: 90%; left: 10%;\n"
                + "                }\n"
                + "                .mdl-grid{\n"
                + "\n"
                + "                }\n"
                + "                .adapGrafica{\n"
                + "                    width: 100%; left: 0%;\n"
                + "                }\n"
                + "                .adapTarjetaGrafica{\n"
                + "                    height: auto;\n"
                + "                    overflow: hidden;\n"
                + "                }\n"
                + "                .titGrafica{\n"
                + "                    font-size: 22px;\n"
                + "                }\n"
                + "                .subGrafica{\n"
                + "                    font-size: 33px; \n"
                + "                }\n"
                + "                .titHorario{\n"
                + "                    font-size: 20px\n"
                + "                }\n"
                + "                .titOtro{\n"
                + "                    font-size: 20px;\n"
                + "                }\n"
                + "                .subOtro{\n"
                + "                    font-size: 15px;\n"
                + "                }\n"
                + ".titulos{font-size: 37px;}"
                + "\n"
                + "\n"
                + "\n"
                + "\n"
                + "            }\n"
                + "            @media screen and (max-width: 839px){\n"
                + "                .adapGrafica{\n"
                + "                    width: 90%; left: 5%;\n"
                + "                }\n"
                + "                .adapTarjetaGrafica{\n"
                + "                    height: auto;\n"
                + "                    overflow: hidden;\n"
                + "                }\n"
                + "                .titGrafica{\n"
                + "                    font-size: 28px;\n"
                + "                }\n"
                + "                .subGrafica{\n"
                + "                    font-size: 40px; \n"
                + "                }\n"
                + "                .tarjetaPequena{\n"
                + "                    height: auto;\n"
                + "                    overflow: hidden;\n"
                + "                }\n"
                + "                .tarjetas{\n"
                + "                    box-shadow: none;\n"
                + "                    border-radius: initial;\n"
                + "                    transform: none;\n"
                + "                    \n"
                + "                }\n"
                + "                .tarjetas:hover{\n"
                + "                    box-shadow: none;\n"
                + "                }\n"
                + "                .iconos{\n"
                + "                    border-radius: initial;\n"
                + "                }\n"
                + "            }\n"
                + "\n"
                + "            @media screen and (max-width: 1024px){\n"
                + "                .titulob{\n"
                + "                    font-size: 0px;\n"
                + "                    position: absolute;\n"
                + "                    float: right;\n"
                + "                }\n"
                + "                .tituloBoldb{\n"
                + "                    font-size: 0px;\n"
                + "                    position: absolute;\n"
                + "                    float: right;\n"
                + "                }\n"
                + "                #cuenta, #salir{\n"
                + "                    display: block;\n"
                + "                }\n"
                + "                .notificacion{\n"
                + "                    padding-left: 50px;\n"
                + "                    padding-right: 50px;\n"
                + "                }\n"
                + "                .editor{\n"
                + "\n"
                + "                }\n"
                + "                .notificacionEditor{\n"
                + "                    padding-left: 50px;\n"
                + "                    padding-right: 50px;\n"
                + "                }\n"
                + "\n"
                + "                body {\n"
                + "                    font-size: calc(0.75em + 1vmin);\n"
                + "                }\n"
                + "                .titGrafica{\n"
                + "                    font-size: 28px;\n"
                + "                }\n"
                + "                .subGrafica{\n"
                + "                    font-size: 50px; \n"
                + "                }\n"
                + "\n"
                + "\n"
                + "            }"
                + "        </style>\n"
                + "        <script>\n"
                + "            window.onload = function () {\n"
                + "                var barrita = document.getElementById('barrita');\n"
                + "                barrita.style.visibility = 'hidden';\n"
                + "                barrita.style.opacity = '0';\n"
                + "            };\n"
                + "        </script>\n"
                + "    </head>\n"
                + "    <body>\n"
                + "        <div id=\"barrita\">\n"
                + "            <div id=\"cargar\" class=\"mdl-progress mdl-js-progress mdl-progress__indeterminate\"><br><center><span class=\"titulo\">Cargando...</span></center></div> \n"
                + "        </div>\n"
                + "        <!-- Always shows a header, even in smaller screens. -->\n"
                + "        <div class=\"mdl-layout mdl-js-layout mdl-layout--fixed-header\">\n"
                + "            <header class=\"mdl-layout__header\" style=\"background-color: transparent;\">\n"
                + "                <div class=\"mdl-layout__header-row\" style=\"background: linear-gradient(to right, #0091EA, #00D4FF);\">\n"
                + "                    <!-- Title -->\n"
                + "                    <div id=\"tarjeta\">&nbsp;Inicio&nbsp;</div><div class=\"centrado\"><span class=\"titulob\">&nbsp;Poli<span class=\"tituloBoldb\">Asistencia</span></span></div>\n"
                + "                    <!-- Add spacer, to align navigation to the right -->\n"
                + "                    <div class=\"mdl-layout-spacer\"></div>\n"
                + "\n"
                + "                    <!-- Navigation. We hide it in small screens. -->\n"
                + "                    <nav class=\"mdl-navigation mdl-layout--large-screen-only\">\n"
                + "                        <button id=\"demo-menu-lower-right\"\n"
                + "                                class=\"persona\">\n"
                + "                            "+_nombre+"\n"
                + "                        </button>\n"
                + "                        <ul class=\"mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect\"\n"
                + "                            for=\"demo-menu-lower-right\">\n"
                + "                            <a href=\"configuracion\"><li class=\"mdl-menu__item\">Configuración de la cuenta</li></a>\n"
                + "                            <a href=\"cerrarSesion\"><li class=\"mdl-menu__item\">Cerrar Sesión</li></a>\n"
                + "                        </ul>\n"
                + "                    </nav>\n"
                + "                </div>\n"
                + "            </header>\n"
                + "            <div class=\"mdl-layout__drawer\">\n"
                + "                <span class=\"titulo\">&nbsp;Poli<span class=\"tituloBold\">Asistencia</span></span>\n"
                + "                <nav class=\"mdl-navigation\">\n"
                + "                    <a class=\"mdl-navigation__link seleccionado\" href=\"#\"><i class=\"material-icons md-36 md-light\">home</i> Inicio</a>\n"
                + "                    <a class=\"mdl-navigation__link disponible\" href=\"horario\" ><i class=\"material-icons md-36 md-dark\">date_range</i> Horario</a>\n"
                + "                    <a class=\"mdl-navigation__link disponible\" href=\"estadisticas\"><i class=\"material-icons md-36 md-dark\">insert_chart</i> Estadisticas</a>\n"
                + "                    <a class=\"mdl-navigation__link disponible\" href=\"notificaciones\"><i class=\"material-icons md-36 md-dark\">list</i> Notificaciones</a>\n"
                + "                    <a class=\"mdl-navigation__link disponible\" href=\"configuracion\"><i class=\"material-icons md-36 md-dark\">settings</i> Configuración</a>\n"
                + "                    <a class=\"mdl-navigation__link disponible\" href=\"cerrarSesion\"><i class=\"material-icons md-36 md-dark\">exit_to_app</i> Cerrar Sesión</a>\n"
                + "\n"
                + "                </nav>\n"
                + "            </div>\n"
                + "            <main class=\"mdl-layout__content\" style=\"background-color: whitesmoke;\">\n"
                + "                <div class=\"mdl-grid center-items\">\n"
                + "                    <div class=\"mdl-cell mdl-cell--3-col\">\n"
                + "                        <a href=\"horario\">\n"
                + "                            <div class=\"tarjetas\">\n"
                + "                                <div class=\"iconos\" style=\"background: linear-gradient(to right, rgb(237, 155, 3), rgb(255, 166, 0)) \">\n"
                + "                                    <i class=\"material-icons md-48 md-light\">date_range</i>\n"
                + "                                </div>\n"
                + "                                <div class=\"descripcion\" style=\"\">\n"
                + "                                    Horario\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                        </a>\n"
                + "                    </div>\n"
                + "                    <div class=\"mdl-cell mdl-cell--3-col\">\n"
                + "                        <a href=\"estadisticas\">\n"
                + "                            <div class=\"tarjetas\">\n"
                + "                                <div class=\"iconos\" style=\"background: linear-gradient(to right, rgb(240, 36, 0), rgb(255, 15, 0)) \">\n"
                + "                                    <i class=\"material-icons md-48 md-light\">insert_chart</i>\n"
                + "                                </div>\n"
                + "                                <div class=\"descripcion\" style=\"\">\n"
                + "                                    Estadisticas de Asistencia\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                        </a>\n"
                + "                    </div>\n"
                + "                    <div class=\"mdl-cell mdl-cell--3-col\">\n"
                + "                        <a href=\"notificaciones\">\n"
                + "                            <div class=\"tarjetas\">\n"
                + "                                <div class=\"iconos\" style=\"background: linear-gradient(to right, rgb(0, 229, 10), rgb(0, 238, 11)) \">\n"
                + "                                    <i class=\"material-icons md-48 md-light\">list</i>\n"
                + "                                </div>\n"
                + "                                <div class=\"descripcion\" style=\"\">\n"
                + "                                    Notificaciones\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                        </a>\n"
                + "                    </div>\n"
                + "                    <div class=\"mdl-cell mdl-cell--3-col\">\n"
                + "                        <a href=\"configuracion\">\n"
                + "                        <div class=\"tarjetas\">\n"
                + "                            <div class=\"iconos\" style=\"background: linear-gradient(to right,  rgb(99, 99, 99), rgb(126, 126, 126)) \">\n"
                + "                                <i class=\"material-icons md-48 md-light\">settings</i>\n"
                + "                            </div>\n"
                + "                            <div class=\"descripcion\" style=\"\">\n"
                + "                                Configuración de la cuenta\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                        </a>\n"
                + "                    </div>\n"
                + "                    <div class=\"mdl-cell mdl-cell--12-col\">\n"
                + "                        <div class=\"tarjetas adapTarjetaGrafica\" style=\"\">\n"
                + "                            <div class=\"iconos adapGrafica\" style=\"\">\n"
                + "                                <canvas id=\"grafica\"></canvas>\n"
                + "                            </div>\n"
                + "                            <div class=\"descripcion adapGrafica\" style=\"\">\n"
                + "                                <br><br>\n"
                + "                                <span style=\"\" class=\"titGrafica\">Días Asistidos en Total</span><br><br><br>\n"
                + "                                <span style=\"\" class=\"subGrafica\">"+ diasTotal +" días</span><br><br><br><br>\n"
                + "                                <center>\n"
                +"<a href=\"estadisticas/asistenciaIndividual\">"
                + "                                    <button class=\"mdl-button mdl-js-button mdl-button--primary\" style=\"color: rgb(240, 36, 0); width: 50%\">\n"
                + "                                        Ver más detalles\n"
                + "                                    </button>\n"
                +"</a>"
                + "                                </center>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                + "                        <div class=\"tarjetas\" style=\"height: 400px;\">\n"
                + "                            <div class=\"descripcion\" style=\"width: 100%\">\n"
                + "                                <br>\n"
                + "                                <span style=\"\" class=\"titHorario\">Grupos de Hoy</span><br><br>\n"
                + "                                <div class=\"ajustarTabla\">\n"
                + "                                   "+obtenerHorarioDiaProfesor(_numero, calendario.get(Calendar.DAY_OF_WEEK)-1)+" "
                + "                                </div>\n"
                + "                                <br>\n"
                + "                                <center>\n"
                +"<a href=\"horario\">"
                + "                                    <button class=\"mdl-button mdl-js-button mdl-button--primary\" style=\"color: rgb(255, 166, 0); width: 50%\">\n"
                + "                                        Ver horario\n"
                + "                                    </button>\n"
                +"</a>"
                + "                                </center>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "\n"
                + "                    </div>\n"
                + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                + "                        <div class=\"tarjetas tarjetaPequena\" style=\" margin-bottom: 20px;\">\n"
                + "                            <div class=\"descripcion\" style=\"width: 100%\">\n"
                + "                                <br><span class=\"titOtro\" style=\" color: rgb(0, 229, 10)\">Ver notificaciones de la escuela</span><br><br>\n"
                + "                                <span class=\"subOtro\" style=\" color: gray\">Da un vistazo a las notificaciones y avisos importantes <br>de la escuela</span><br>\n"
                + "                                <center>\n"
                +"<a href=\"notificaciones\">"
                + "                                    <button class=\"mdl-button mdl-js-button mdl-button--primary\" style=\"color: rgb(0, 229, 10); width: 50%\">\n"
                + "                                        Ver notificaciones\n"
                + "                                    </button>\n"
                +"</a>"
                + "                                </center>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                        <div class=\"tarjetas\" style=\"height: 190px;\">\n"
                + "                            <div class=\"iconos\" style=\"width: 30%; background: linear-gradient(to right,  rgb(99, 99, 99), rgb(126, 126, 126));\">\n"
                + "                                <i class=\"material-icons md-48 md-light\" style=\"font-size: 95px;\">account_circle</i>\n"
                + "                            </div>\n"
                + "                            <div class=\"descripcion\" style=\"width: 70%\">\n"
                + "                                <br><span class=\"titOtro\" style=\" color: rgb(126, 126, 126)\">Modifica tus datos</span><br><br>\n"
                + "                                <span class=\"subOtro\" style=\" color: gray\">Puedes modificar los datos de tu cuenta <br>entrando a configuración</span><br>\n"
                + "                                <center>\n"
                +"<a href=\"configuracion\">"
                + "                                    <button class=\"mdl-button mdl-js-button mdl-button--primary\" style=\"color: rgb(126, 126, 126); width: 50%\">\n"
                + "                                        Ir a configuración\n"
                + "                                    </button>\n"
                +"</a>"
                + "                                </center>\n"
                + "                            </div>\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "                    <div class=\"mdl-cell mdl-cell--6-col\">\n"
                + "\n"
                + "                    </div>\n"
                + "                </div>\n"
                + "\n"
                + "            </main>\n"
                + "        </div>\n"
                + "        <script>\n"
                + "       "+scriptGeneral+" "
                + "        </script>\n"
                + "    </body>\n"
                + "</html>\n"
                + "";
        return _inicio;
    }

    private static java.util.List<java.lang.Object> asistenciaInd(java.lang.String idPer, java.lang.String mes) {
        serviciosWebProfesor.Profesor_Service service = new serviciosWebProfesor.Profesor_Service();
        serviciosWebProfesor.Profesor port = service.getProfesorPort();
        return port.asistenciaInd(idPer, mes);
    }

    private static String obtenerHorarioDiaProfesor(java.lang.String numero, int diaSemana) {
        serviciosWebProfesor.Profesor_Service service = new serviciosWebProfesor.Profesor_Service();
        serviciosWebProfesor.Profesor port = service.getProfesorPort();
        return port.obtenerHorarioDiaProfesor(numero, diaSemana);
    }


}
